import 'dart:io';

import 'package:path/path.dart' as p;

/// The generated file holding the curated notes, relative to the repo root.
const notesBundleFile =
    'packages/appstein_engine/lib/src/notes/bundled_notes.g.dart';

/// The curated notes folder, relative to the repo root (spec §5.1, §6.4).
const notesFolder = 'notes';

/// The YAML files in `notes/` of the repo at [repoRoot], by file name, with
/// `\n` line endings and a final newline.
Map<String, String> readNotesSources(String repoRoot) {
  final files =
      Directory(p.join(repoRoot, notesFolder))
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.yaml'))
          .toList()
        ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));
  return {
    for (final file in files)
      p.basename(file.path): _withFinalNewline(
        file.readAsStringSync().replaceAll('\r\n', '\n'),
      ),
  };
}

String _withFinalNewline(String text) => text.endsWith('\n') ? text : '$text\n';

/// The Dart source of [notesBundleFile] for [sources] (file name to YAML).
///
/// Each file becomes a raw multi-line string, so its text is kept exactly:
/// Dart drops the line break right after the opening quotes, and `r` turns
/// off escapes and `$` interpolation. A file holding `'''` uses `"""`
/// instead. Throws an [ArgumentError] when a file holds both.
String renderNotesBundle(Map<String, String> sources) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_notes.dart from notes/*.yaml. Do not')
    ..writeln(
      '// edit: edit the YAML, then run `fvm dart run tool/gen_notes.dart`.',
    )
    ..writeln()
    ..writeln('/// The curated notes compiled into Appstein (spec §6.4): file')
    ..writeln('/// name to YAML text.')
    ..writeln('const bundledNotes = <String, String>{');
  for (final name in sources.keys.toList()..sort()) {
    final text = _withFinalNewline(sources[name]!);
    final quote = !text.contains("'''")
        ? "'''"
        : !text.contains('"""')
        ? '"""'
        : throw ArgumentError.value(
            name,
            'sources',
            "holds both ''' and \"\"\", so it can't be a raw Dart string",
          );
    buffer
      ..writeln("  '$name': r$quote")
      ..write(text)
      ..writeln('$quote,');
  }
  buffer.writeln('};');
  return buffer.toString();
}
