import 'dart:convert';

import '../knowledge/input_hash.dart';
import '../knowledge/plain_text.dart';

/// The version of the engine's own page templates (spec §6.9): `README.md`,
/// `dependencies.md`, `decisions.md` and the frame every page shares. Bump
/// it when one of them changes shape, so the pages it renders show a
/// one-time diff.
const docsEngineVersion = '2';

/// The line under the marker of every generated page.
const docNotice =
    '> Generated by Appstein; edits are overwritten. Write `///` doc '
    'comments or a team note instead.';

const _prefix = '<!-- appstein:generated ';
final _markerLine = RegExp(
  r'^<!-- appstein:generated templates=(\S+) body=([0-9a-f]{64}) -->$',
);
final _template = RegExp(r'^([^@,\s]+)@([^@,\s]+)$');

/// The marker in the first line of a generated page (spec §6.9). It tells
/// Appstein the page is its own, and tells a page that was edited by hand
/// from one that fell behind.
///
/// It holds no hash of the page's inputs. Those are whole knowledge files,
/// so one new class would change the first line of every feature page.
/// Whether a page is behind is found by rendering it again and comparing.
final class DocMarker {
  /// Creates a marker.
  const DocMarker({required this.templates, required this.body});

  /// Who rendered the page, each with its template version, in the order
  /// they contributed: a pack's id with the pack's version, or `engine` with
  /// [docsEngineVersion]. It is not the Appstein version, which would change
  /// every page at every release.
  final Map<String, String> templates;

  /// The hash of the page's body ([bodyHash]), as SHA-256 hex. A page whose
  /// body no longer matches it was edited by hand.
  final String body;

  /// The marker as the page's first line.
  String get line {
    final names = [
      for (final MapEntry(:key, :value) in templates.entries) '$key@$value',
    ].join(',');
    return '${_prefix}templates=$names body=$body -->';
  }

  /// The marker in the first line of [text], or null when that line isn't
  /// one. A byte order mark before it and a carriage return after it are
  /// allowed: an editor or a Windows checkout adds them.
  static DocMarker? of(String text) {
    final plain = withoutBom(text);
    final end = plain.indexOf(RegExp(r'[\r\n]'));
    final match = _markerLine.firstMatch(
      end < 0 ? plain : plain.substring(0, end),
    );
    if (match == null) return null;
    final templates = <String, String>{};
    for (final part in match[1]!.split(',')) {
      final template = _template.firstMatch(part);
      if (template == null) return null;
      templates[template[1]!] = template[2]!;
    }
    return DocMarker(templates: templates, body: match[2]!);
  }
}

/// Whether [text] is a generated page that git left in a merge conflict.
///
/// The body hash is in a page's first line, so when two branches change the
/// same page, git always puts its conflict there: line 1 is `<<<<<<<` and
/// line 2 is one side's marker. Such a file is still Appstein's page, and
/// rendering it again resolves the conflict (spec §6.9). Only this exact
/// shape counts, so a person's note that merely contains conflict lines or
/// quotes a marker further down is never taken for a page.
bool isConflictedPage(String text) {
  final lines = plainLines(text).split('\n');
  return lines.length > 1 &&
      lines.first.startsWith('<<<<<<<') &&
      _markerLine.hasMatch(lines[1]);
}

/// [text] without a byte order mark, and with every line ending as `\n`.
/// Generated pages are compared in this form, so a checkout that converts
/// line endings is never taken for a change (spec §6.9).
String plainLines(String text) =>
    withoutBom(text).replaceAll('\r\n', '\n').replaceAll('\r', '\n');

final _endingBreaks = RegExp(r'\n*$');

/// [text] in the form [plainLines] gives, without the line breaks at its
/// end. Two pages that are equal in this form differ only in line endings, a
/// byte order mark, or blank lines at the end, which an editor adds or
/// strips: they count as the same page (spec §6.9).
String withoutEndingBreaks(String text) =>
    plainLines(text).replaceFirst(_endingBreaks, '');

/// Whether [text] starts as a generated page does, or is empty. A page is
/// written through a temporary file; one that looks like this is what an
/// interrupted write left behind, never a person's file.
bool isLeftoverPageWrite(String text) {
  final plain = withoutBom(text);
  return plain.isEmpty || plain.startsWith(_prefix);
}

/// The text of a generated page: [marker]'s line, then [body].
String markedPage(DocMarker marker, String body) => '${marker.line}\n$body';

/// The body of a page [text] that has a marker: everything after its first
/// line, in the form [plainLines] gives, ending in exactly one line break as
/// every rendered body does. So blank lines added or stripped at the end of
/// the file never make a page look edited by hand.
String bodyOf(String text) {
  final plain = plainLines(text);
  final end = plain.indexOf('\n');
  if (end < 0) return '';
  final body = withoutEndingBreaks(plain.substring(end + 1));
  return body.isEmpty ? '' : '$body\n';
}

/// The SHA-256 of [body] as hex, in the form [plainLines] gives, so the
/// hash is the same whatever line endings the file has.
String bodyHash(String body) => sha256Hex(utf8.encode(plainLines(body)));
