import 'dart:convert';

import '../knowledge/input_hash.dart';
import '../knowledge/plain_text.dart';

/// The version of the engine's own page templates (spec §6.9): `README.md`,
/// `dependencies.md`, `decisions.md` and the frame every page shares. Bump
/// it when one of them changes shape, so the pages it renders show a
/// one-time diff.
const docsEngineVersion = '1';

/// The line under the marker of every generated page.
const docNotice =
    '> Generated by Appstein; edits are overwritten. Write `///` doc '
    'comments or a team note instead.';

const _prefix = '<!-- appstein:generated ';
final _markerLine = RegExp(
  r'^<!-- appstein:generated templates=(\S+) body=([0-9a-f]{64}) -->$',
);
final _template = RegExp(r'^([^@,\s]+)@([^@,\s]+)$');

/// The marker in the first line of a generated page (spec §6.9). It tells
/// Appstein the page is its own, and tells a page that was edited by hand
/// from one that fell behind.
///
/// It holds no hash of the page's inputs. Those are whole knowledge files,
/// so one new class would change the first line of every feature page.
/// Whether a page is behind is found by rendering it again and comparing.
final class DocMarker {
  /// Creates a marker.
  const DocMarker({required this.templates, required this.body});

  /// Who rendered the page, each with its template version, in the order
  /// they contributed: a pack's id with the pack's version, or `engine` with
  /// [docsEngineVersion]. It is not the Appstein version, which would change
  /// every page at every release.
  final Map<String, String> templates;

  /// The hash of the page's body ([bodyHash]), as SHA-256 hex. A page whose
  /// body no longer matches it was edited by hand.
  final String body;

  /// The marker as the page's first line.
  String get line {
    final names = [
      for (final MapEntry(:key, :value) in templates.entries) '$key@$value',
    ].join(',');
    return '${_prefix}templates=$names body=$body -->';
  }

  /// The marker in the first line of [text], or null when that line isn't
  /// one. A byte order mark before it and a carriage return after it are
  /// allowed: an editor or a Windows checkout adds them.
  static DocMarker? of(String text) {
    final plain = withoutBom(text);
    final end = plain.indexOf(RegExp(r'[\r\n]'));
    final match = _markerLine.firstMatch(
      end < 0 ? plain : plain.substring(0, end),
    );
    if (match == null) return null;
    final templates = <String, String>{};
    for (final part in match[1]!.split(',')) {
      final template = _template.firstMatch(part);
      if (template == null) return null;
      templates[template[1]!] = template[2]!;
    }
    return DocMarker(templates: templates, body: match[2]!);
  }
}

/// [text] without a byte order mark, and with every line ending as `\n`.
/// Generated pages are compared in this form, so a checkout that converts
/// line endings is never taken for a change (spec §6.9).
String plainLines(String text) =>
    withoutBom(text).replaceAll('\r\n', '\n').replaceAll('\r', '\n');

/// The text of a generated page: [marker]'s line, then [body].
String markedPage(DocMarker marker, String body) => '${marker.line}\n$body';

/// The body of a page [text] that has a marker: everything after its first
/// line, in the form [plainLines] gives.
String bodyOf(String text) {
  final plain = plainLines(text);
  final end = plain.indexOf('\n');
  return end < 0 ? '' : plain.substring(end + 1);
}

/// The SHA-256 of [body] as hex, in the form [plainLines] gives, so the
/// hash is the same whatever line endings the file has.
String bodyHash(String body) => sha256Hex(utf8.encode(plainLines(body)));
